const Images = {
  number: require('../Images/5number.png'),
  Green_Star: require('../Images/greenstar_icon.png'),
  White_Star: require('../Images/WhiteStar_icon.png'),
  Gridle: require('../Images/Gridle.png'),
  No_1: require('../Images/No1.png'),
  No_2: require('../Images/No2.png'),
  No_3: require('../Images/No3.png'),
  No_4: require('../Images/No4.png'),
  No_5: require('../Images/No5.png'),
  No_6: require('../Images/No6.png'),
  No_7: require('../Images/No7.png'),
  No_8: require('../Images/No8.png'),
  No_9: require('../Images/No9.png'),
  Bg_red: require('../Images/Bg_red.png'),
  Bg_green: require('../Images/Bg_green.png'),
  Bg_percentage: require('../Images/Bg_percentage_.png'),
  Bg_pink: require('../Images/Bg_pink.png'),
  Bg_number: require('../Images/Bg_number_.png'),
  Bg_Red_number: require('../Images/Bg_Red_number_.png'),
};
export default Images;
